FROM jekyll/builder:stable AS builder

COPY . /src/
WORKDIR /src

RUN chown -R jekyll:jekyll /src && bundle install

ENV LANG en_US.UTF-8

RUN jekyll build

FROM nginx:1.16-alpine

COPY --from=builder /src/_site/ /usr/share/nginx/html/
